package com.esi911.webeoc7.api._1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "API", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", wsdlLocation = "file:/C:/Users/pcoleman/WebEOC.xml")
public class API extends Service {

	private final static URL API_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.esi911.webeoc7.api._1.API.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.esi911.webeoc7.api._1.API.class.getResource(".");
			url = new URL(baseUrl, "file:/C:/Users/pcoleman/WebEOC.xml");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/pcoleman/WebEOC.xml', retrying as a local file");
			logger.warning(e.getMessage());
		}
		API_WSDL_LOCATION = url;
	}

	public API(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public API(URL wsdlLocation) {
		super(wsdlLocation, new QName("urn:com:esi911:webeoc7:api:1.0", "API"));
	}

	public API() {
		super(API_WSDL_LOCATION, new QName("urn:com:esi911:webeoc7:api:1.0",
				"API"));
	}

	/**
	 * 
	 * @return returns APISoap
	 */
	@WebEndpoint(name = "APISoap")
	public APISoap getAPISoap() {
		return super.getPort(new QName("urn:com:esi911:webeoc7:api:1.0",
				"APISoap"), APISoap.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns APISoap
	 */
	@WebEndpoint(name = "APISoap")
	public APISoap getAPISoap(WebServiceFeature... features) {
		return super.getPort(new QName("urn:com:esi911:webeoc7:api:1.0",
				"APISoap"), APISoap.class, features);
	}

}
