
package com.esi911.webeoc7.api._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "APISoap", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface APISoap {


    /**
     * Attach a file to a WebEOC board entry.
     * 
     * @param attachmentFieldName
     * @param attachmentFileData
     * @param dataId
     * @param inputViewName
     * @param attachmentFileName
     * @param credentials
     * @param boardName
     */
    @WebMethod(operationName = "AddAttachment", action = "urn:com:esi911:webeoc7:api:1.0/AddAttachment")
    @RequestWrapper(localName = "AddAttachment", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.AddAttachment")
    @ResponseWrapper(localName = "AddAttachmentResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.AddAttachmentResponse")
    public void addAttachment(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName,
        @WebParam(name = "InputViewName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String inputViewName,
        @WebParam(name = "AttachmentFieldName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String attachmentFieldName,
        @WebParam(name = "DataId", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        int dataId,
        @WebParam(name = "AttachmentFileData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        byte[] attachmentFileData,
        @WebParam(name = "AttachmentFileName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String attachmentFileName);

    /**
     * Get a list of the WebEOC positions. Administrator access required
     * 
     * @param credentials
     * @return
     *     returns com.esi911.webeoc7.api._1.ArrayOfString
     */
    @WebMethod(operationName = "GetPositions", action = "urn:com:esi911:webeoc7:api:1.0/GetPositions")
    @WebResult(name = "GetPositionsResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetPositions", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetPositions")
    @ResponseWrapper(localName = "GetPositionsResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetPositionsResponse")
    public ArrayOfString getPositions(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials);

    /**
     * Get a list of the WebEOC users that belong to specific position. Administrator access required. Raises an exception if the positions does not exist.
     * 
     * @param credentials
     * @param positionName
     * @return
     *     returns com.esi911.webeoc7.api._1.ArrayOfWebEOCUser
     */
    @WebMethod(operationName = "GetUsersByPosition", action = "urn:com:esi911:webeoc7:api:1.0/GetUsersByPosition")
    @WebResult(name = "GetUsersByPositionResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetUsersByPosition", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetUsersByPosition")
    @ResponseWrapper(localName = "GetUsersByPositionResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetUsersByPositionResponse")
    public ArrayOfWebEOCUser getUsersByPosition(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "PositionName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String positionName);

    /**
     * Get the list of positions that a user can fill. Administrator access required.
     * 
     * @param userName
     * @param credentials
     * @return
     *     returns com.esi911.webeoc7.api._1.ArrayOfString
     */
    @WebMethod(operationName = "GetPositionsForUser", action = "urn:com:esi911:webeoc7:api:1.0/GetPositionsForUser")
    @WebResult(name = "GetPositionsForUserResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetPositionsForUser", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetPositionsForUser")
    @ResponseWrapper(localName = "GetPositionsForUserResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetPositionsForUserResponse")
    public ArrayOfString getPositionsForUser(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "UserName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String userName);

    /**
     * Add a user to the database. Administrator access required. An exception will be raised if a user already exists with the same username.  If a color value is supplied, an exception will be raised if the value is not a valid color string(6 digit hexadecimal string)
     * 
     * @param credentials
     * @param password
     * @param userToAdd
     */
    @WebMethod(operationName = "AddUser", action = "urn:com:esi911:webeoc7:api:1.0/AddUser")
    @RequestWrapper(localName = "AddUser", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.AddUser")
    @ResponseWrapper(localName = "AddUserResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.AddUserResponse")
    public void addUser(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "UserToAdd", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCUser userToAdd,
        @WebParam(name = "Password", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String password);

    /**
     * Add a user to a position assignment. Administrator access required. An exception will be raised if the user or position does not exist
     * 
     * @param position
     * @param userName
     * @param credentials
     */
    @WebMethod(operationName = "AddUserToPosition", action = "urn:com:esi911:webeoc7:api:1.0/AddUserToPosition")
    @RequestWrapper(localName = "AddUserToPosition", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.AddUserToPosition")
    @ResponseWrapper(localName = "AddUserToPositionResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.AddUserToPositionResponse")
    public void addUserToPosition(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "UserName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String userName,
        @WebParam(name = "Position", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String position);

    /**
     * Remove a user from a position assignment.  Administrator access required. An exception will be raised if the user or position does not exist
     * 
     * @param position
     * @param userName
     * @param credentials
     */
    @WebMethod(operationName = "RemoveUserFromPosition", action = "urn:com:esi911:webeoc7:api:1.0/RemoveUserFromPosition")
    @RequestWrapper(localName = "RemoveUserFromPosition", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.RemoveUserFromPosition")
    @ResponseWrapper(localName = "RemoveUserFromPositionResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.RemoveUserFromPositionResponse")
    public void removeUserFromPosition(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "UserName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String userName,
        @WebParam(name = "Position", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String position);

    /**
     * Delete a user from WebEOC. Administrator access required. An exception will be raised if the user does not exist or if the user is the same user supplied in the credentials.  Returns false if the user was unable to be deleted due to position member.  Returns true if the user was deleted
     * 
     * @param userName
     * @param credentials
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "DeleteUserIfNoPositions", action = "urn:com:esi911:webeoc7:api:1.0/DeleteUserIfNoPositions")
    @WebResult(name = "DeleteUserIfNoPositionsResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "DeleteUserIfNoPositions", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.DeleteUserIfNoPositions")
    @ResponseWrapper(localName = "DeleteUserIfNoPositionsResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.DeleteUserIfNoPositionsResponse")
    public boolean deleteUserIfNoPositions(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "UserName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String userName);

    /**
     * Delete a user from WebEOC. Administrator access required. An exception will be raised if the user does not exist or if the user is the same user supplied in the credentials or if the user is not deleteable (WebEOC Administrator)
     * 
     * @param userName
     * @param credentials
     */
    @WebMethod(operationName = "DeleteUser", action = "urn:com:esi911:webeoc7:api:1.0/DeleteUser")
    @RequestWrapper(localName = "DeleteUser", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.DeleteUser")
    @ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.DeleteUserResponse")
    public void deleteUser(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "UserName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String userName);

    /**
     * Get a list of the WebEOC boards. Administrator access required
     * 
     * @param credentials
     * @return
     *     returns com.esi911.webeoc7.api._1.ArrayOfString
     */
    @WebMethod(operationName = "GetBoardNames", action = "urn:com:esi911:webeoc7:api:1.0/GetBoardNames")
    @WebResult(name = "GetBoardNamesResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetBoardNames", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetBoardNames")
    @ResponseWrapper(localName = "GetBoardNamesResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetBoardNamesResponse")
    public ArrayOfString getBoardNames(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials);

    /**
     * Get the list of Input views for a specific board. Administrator access required
     * 
     * @param credentials
     * @param boardName
     * @return
     *     returns com.esi911.webeoc7.api._1.ArrayOfString
     */
    @WebMethod(operationName = "GetInputViews", action = "urn:com:esi911:webeoc7:api:1.0/GetInputViews")
    @WebResult(name = "GetInputViewsResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetInputViews", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetInputViews")
    @ResponseWrapper(localName = "GetInputViewsResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetInputViewsResponse")
    public ArrayOfString getInputViews(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName);

    /**
     * Get the list of Display views for a specific board. Administrator access required
     * 
     * @param credentials
     * @param boardName
     * @return
     *     returns com.esi911.webeoc7.api._1.ArrayOfString
     */
    @WebMethod(operationName = "GetDisplayViews", action = "urn:com:esi911:webeoc7:api:1.0/GetDisplayViews")
    @WebResult(name = "GetDisplayViewsResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetDisplayViews", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetDisplayViews")
    @ResponseWrapper(localName = "GetDisplayViewsResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetDisplayViewsResponse")
    public ArrayOfString getDisplayViews(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName);

    /**
     * Get the list of fields for a particular view. Administrator access required.
     * 
     * @param viewName
     * @param credentials
     * @param boardName
     * @return
     *     returns com.esi911.webeoc7.api._1.ArrayOfString
     */
    @WebMethod(operationName = "GetViewFields", action = "urn:com:esi911:webeoc7:api:1.0/GetViewFields")
    @WebResult(name = "GetViewFieldsResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetViewFields", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetViewFields")
    @ResponseWrapper(localName = "GetViewFieldsResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetViewFieldsResponse")
    public ArrayOfString getViewFields(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName,
        @WebParam(name = "ViewName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String viewName);

    /**
     * Add a new entry to a WebEOC board.
     * 
     * @param xmlData
     * @param inputViewName
     * @param credentials
     * @param boardName
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AddData", action = "urn:com:esi911:webeoc7:api:1.0/AddData")
    @WebResult(name = "AddDataResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "AddData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.AddData")
    @ResponseWrapper(localName = "AddDataResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.AddDataResponse")
    public int addData(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName,
        @WebParam(name = "InputViewName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String inputViewName,
        @WebParam(name = "XmlData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String xmlData);

    /**
     * Update an existing entry in a WebEOC board.
     * 
     * @param dataId
     * @param xmlData
     * @param inputViewName
     * @param credentials
     * @param boardName
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UpdateData", action = "urn:com:esi911:webeoc7:api:1.0/UpdateData")
    @WebResult(name = "UpdateDataResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "UpdateData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.UpdateData")
    @ResponseWrapper(localName = "UpdateDataResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.UpdateDataResponse")
    public int updateData(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName,
        @WebParam(name = "InputViewName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String inputViewName,
        @WebParam(name = "XmlData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String xmlData,
        @WebParam(name = "DataId", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        int dataId);

    /**
     * Batch method for adding/updating entires in a WebEOC board.
     * 
     * @param xmlData
     * @param inputViewName
     * @param credentials
     * @param boardName
     * @return
     *     returns com.esi911.webeoc7.api._1.ArrayOfInt
     */
    @WebMethod(operationName = "UpdateDataBatch", action = "urn:com:esi911:webeoc7:api:1.0/UpdateDataBatch")
    @WebResult(name = "UpdateDataBatchResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "UpdateDataBatch", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.UpdateDataBatch")
    @ResponseWrapper(localName = "UpdateDataBatchResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.UpdateDataBatchResponse")
    public ArrayOfInt updateDataBatch(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName,
        @WebParam(name = "InputViewName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String inputViewName,
        @WebParam(name = "XmlData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String xmlData);

    /**
     * 
     * @param xmlData
     * @param inputViewName
     * @param relatedTable
     * @param credentials
     * @param relatedDataId
     * @param boardName
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AddRelatedData", action = "urn:com:esi911:webeoc7:api:1.0/AddRelatedData")
    @WebResult(name = "AddRelatedDataResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "AddRelatedData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.AddRelatedData")
    @ResponseWrapper(localName = "AddRelatedDataResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.AddRelatedDataResponse")
    public int addRelatedData(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName,
        @WebParam(name = "InputViewName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String inputViewName,
        @WebParam(name = "XmlData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String xmlData,
        @WebParam(name = "RelatedTable", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String relatedTable,
        @WebParam(name = "RelatedDataId", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        int relatedDataId);

    /**
     * 
     * @param dataId
     * @param xmlData
     * @param inputViewName
     * @param relatedTable
     * @param credentials
     * @param relatedDataId
     * @param boardName
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UpdateRelatedData", action = "urn:com:esi911:webeoc7:api:1.0/UpdateRelatedData")
    @WebResult(name = "UpdateRelatedDataResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "UpdateRelatedData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.UpdateRelatedData")
    @ResponseWrapper(localName = "UpdateRelatedDataResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.UpdateRelatedDataResponse")
    public int updateRelatedData(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName,
        @WebParam(name = "InputViewName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String inputViewName,
        @WebParam(name = "XmlData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String xmlData,
        @WebParam(name = "RelatedTable", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String relatedTable,
        @WebParam(name = "RelatedDataId", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        int relatedDataId,
        @WebParam(name = "DataId", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        int dataId);

    /**
     * 
     * @param displayViewName
     * @param credentials
     * @param boardName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetData", action = "urn:com:esi911:webeoc7:api:1.0/GetData")
    @WebResult(name = "GetDataResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetData")
    @ResponseWrapper(localName = "GetDataResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetDataResponse")
    public String getData(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName,
        @WebParam(name = "DisplayViewName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String displayViewName);

    /**
     * 
     * @param viewFilterNames
     * @param displayViewName
     * @param credentials
     * @param xmlUserFilter
     * @param boardName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFilteredData", action = "urn:com:esi911:webeoc7:api:1.0/GetFilteredData")
    @WebResult(name = "GetFilteredDataResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetFilteredData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetFilteredData")
    @ResponseWrapper(localName = "GetFilteredDataResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetFilteredDataResponse")
    public String getFilteredData(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName,
        @WebParam(name = "DisplayViewName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String displayViewName,
        @WebParam(name = "ViewFilterNames", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        ArrayOfString viewFilterNames,
        @WebParam(name = "XmlUserFilter", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String xmlUserFilter);

    /**
     * 
     * @param viewFilterNames
     * @param displayViewName
     * @param customFilter
     * @param credentials
     * @param xmlUserFilter
     * @param boardName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFilteredDataV2", action = "urn:com:esi911:webeoc7:api:1.0/GetFilteredDataV2")
    @WebResult(name = "GetFilteredDataV2Result", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetFilteredDataV2", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetFilteredDataV2")
    @ResponseWrapper(localName = "GetFilteredDataV2Response", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetFilteredDataV2Response")
    public String getFilteredDataV2(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName,
        @WebParam(name = "DisplayViewName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String displayViewName,
        @WebParam(name = "ViewFilterNames", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        ArrayOfString viewFilterNames,
        @WebParam(name = "XmlUserFilter", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String xmlUserFilter,
        @WebParam(name = "CustomFilter", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        CustomFilter customFilter);

    /**
     * Get the board entries that have been added or updated since UpdatedTime
     * 
     * @param displayViewName
     * @param credentials
     * @param boardName
     * @param updatedTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUpdatedData", action = "urn:com:esi911:webeoc7:api:1.0/GetUpdatedData")
    @WebResult(name = "GetUpdatedDataResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetUpdatedData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetUpdatedData")
    @ResponseWrapper(localName = "GetUpdatedDataResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetUpdatedDataResponse")
    public String getUpdatedData(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName,
        @WebParam(name = "DisplayViewName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String displayViewName,
        @WebParam(name = "UpdatedTime", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        XMLGregorianCalendar updatedTime);

    /**
     * 
     * @param displayViewName
     * @param dataId
     * @param credentials
     * @param boardName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDataByDataId", action = "urn:com:esi911:webeoc7:api:1.0/GetDataByDataId")
    @WebResult(name = "GetDataByDataIdResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetDataByDataId", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetDataByDataId")
    @ResponseWrapper(localName = "GetDataByDataIdResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetDataByDataIdResponse")
    public String getDataByDataId(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "BoardName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String boardName,
        @WebParam(name = "DisplayViewName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String displayViewName,
        @WebParam(name = "DataId", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        int dataId);

    /**
     * 
     * @param credentials
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Ping", action = "urn:com:esi911:webeoc7:api:1.0/Ping")
    @WebResult(name = "PingResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "Ping", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.PingResponse")
    public String ping(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials);

    /**
     * 
     * @param xmlStandardData
     * @param credentials
     */
    @WebMethod(operationName = "PostStandardData", action = "urn:com:esi911:webeoc7:api:1.0/PostStandardData")
    @RequestWrapper(localName = "PostStandardData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.PostStandardData")
    @ResponseWrapper(localName = "PostStandardDataResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.PostStandardDataResponse")
    public void postStandardData(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "XmlStandardData", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String xmlStandardData);

    /**
     * Get the list of incidents that a specific user has access to.
     * 
     * @param credentials
     * @return
     *     returns com.esi911.webeoc7.api._1.ArrayOfString
     */
    @WebMethod(operationName = "GetIncidents", action = "urn:com:esi911:webeoc7:api:1.0/GetIncidents")
    @WebResult(name = "GetIncidentsResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetIncidents", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetIncidents")
    @ResponseWrapper(localName = "GetIncidentsResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetIncidentsResponse")
    public ArrayOfString getIncidents(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials);

    /**
     * Add an incident to WebEOC
     * 
     * @param _default
     * @param incidentName
     * @param credentials
     * @param incidentDateTime
     */
    @WebMethod(operationName = "AddIncident", action = "urn:com:esi911:webeoc7:api:1.0/AddIncident")
    @RequestWrapper(localName = "AddIncident", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.AddIncident")
    @ResponseWrapper(localName = "AddIncidentResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.AddIncidentResponse")
    public void addIncident(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "IncidentName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String incidentName,
        @WebParam(name = "IncidentDateTime", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        XMLGregorianCalendar incidentDateTime,
        @WebParam(name = "Default", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        boolean _default);

    /**
     * Get a DataTable of lists. Administrator access required
     * 
     * @param credentials
     * @return
     *     returns com.esi911.webeoc7.api._1.GetListsResponse.GetListsResult
     */
    @WebMethod(operationName = "GetLists", action = "urn:com:esi911:webeoc7:api:1.0/GetLists")
    @WebResult(name = "GetListsResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetLists", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetLists")
    @ResponseWrapper(localName = "GetListsResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetListsResponse")
    public com.esi911.webeoc7.api._1.GetListsResponse.GetListsResult getLists(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials);

    /**
     * Get a DataTable of items in a WebEOC list. Administrator access required
     * 
     * @param listId
     * @param credentials
     * @return
     *     returns com.esi911.webeoc7.api._1.GetListItemsResponse.GetListItemsResult
     */
    @WebMethod(operationName = "GetListItems", action = "urn:com:esi911:webeoc7:api:1.0/GetListItems")
    @WebResult(name = "GetListItemsResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetListItems", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetListItems")
    @ResponseWrapper(localName = "GetListItemsResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetListItemsResponse")
    public com.esi911.webeoc7.api._1.GetListItemsResponse.GetListItemsResult getListItems(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "listId", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        int listId);

    /**
     * Get a DataTable of items in a WebEOC list that a specific user has access to. Administrator access required
     * 
     * @param listName
     * @param credentials
     * @return
     *     returns com.esi911.webeoc7.api._1.GetListItemsByListNameResponse.GetListItemsByListNameResult
     */
    @WebMethod(operationName = "GetListItemsByListName", action = "urn:com:esi911:webeoc7:api:1.0/GetListItemsByListName")
    @WebResult(name = "GetListItemsByListNameResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "GetListItemsByListName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetListItemsByListName")
    @ResponseWrapper(localName = "GetListItemsByListNameResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.GetListItemsByListNameResponse")
    public com.esi911.webeoc7.api._1.GetListItemsByListNameResponse.GetListItemsByListNameResult getListItemsByListName(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "listName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String listName);

    /**
     * Save a WebEOC list. Administrator access required
     * 
     * @param listName
     * @param listId
     * @param credentials
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SaveList", action = "urn:com:esi911:webeoc7:api:1.0/SaveList")
    @WebResult(name = "SaveListResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "SaveList", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.SaveList")
    @ResponseWrapper(localName = "SaveListResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.SaveListResponse")
    public int saveList(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "listId", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        int listId,
        @WebParam(name = "listName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String listName);

    /**
     * Delete a WebEOC list. Administrator access required
     * 
     * @param listId
     * @param credentials
     */
    @WebMethod(operationName = "DeleteList", action = "urn:com:esi911:webeoc7:api:1.0/DeleteList")
    @RequestWrapper(localName = "DeleteList", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.DeleteList")
    @ResponseWrapper(localName = "DeleteListResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.DeleteListResponse")
    public void deleteList(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "listId", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        int listId);

    /**
     * Save a WebEOC list item. Administrator access required
     * 
     * @param listItemId
     * @param listItemColor
     * @param listId
     * @param listItemName
     * @param credentials
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SaveListItem", action = "urn:com:esi911:webeoc7:api:1.0/SaveListItem")
    @WebResult(name = "SaveListItemResult", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
    @RequestWrapper(localName = "SaveListItem", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.SaveListItem")
    @ResponseWrapper(localName = "SaveListItemResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.SaveListItemResponse")
    public int saveListItem(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "listId", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        int listId,
        @WebParam(name = "listItemId", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        int listItemId,
        @WebParam(name = "listItemName", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String listItemName,
        @WebParam(name = "listItemColor", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        String listItemColor);

    /**
     * Delete a WebEOC list item. Administrator access required
     * 
     * @param listItemId
     * @param credentials
     */
    @WebMethod(operationName = "DeleteListItem", action = "urn:com:esi911:webeoc7:api:1.0/DeleteListItem")
    @RequestWrapper(localName = "DeleteListItem", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.DeleteListItem")
    @ResponseWrapper(localName = "DeleteListItemResponse", targetNamespace = "urn:com:esi911:webeoc7:api:1.0", className = "com.esi911.webeoc7.api._1.DeleteListItemResponse")
    public void deleteListItem(
        @WebParam(name = "credentials", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        WebEOCCredentials credentials,
        @WebParam(name = "listItemId", targetNamespace = "urn:com:esi911:webeoc7:api:1.0")
        int listItemId);

}
