#!/bin/sh

# A helper script we made. (SJM)

# prompt a sudo password request
sudo uptime

cd ~/geoserver/src/community/featuretypebuilder/
mvn clean install
sudo cp target/featuretypebuilder-1.0-SNAPSHOT.jar /var/lib/tomcat6/webapps/geoserver/WEB-INF/lib
sudo service tomcat6 restart
